# pnnx model stat
# model inputshape = [1,1,192,320]f32
# FLOPS = 7.945G
# memory OPS = 142.122M

import os
import numpy as np
import tempfile, zipfile
import torch
import torch.nn as nn
import torch.nn.functional as F
try:
    import torchvision
    import torchaudio
except:
    pass

class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()

        self.down_block1_conv1 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=1, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.down_block1_relu = nn.LeakyReLU(negative_slope=0.01)
        self.down_block1_conv21 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=33, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.down_block1_conv22 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.pnnx_unique_0 = nn.LeakyReLU(negative_slope=0.01)
        self.down_block1_conv31 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=65, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.down_block1_conv32 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.pnnx_unique_1 = nn.LeakyReLU(negative_slope=0.01)
        self.down_block1_bn = nn.BatchNorm2d(affine=True, eps=1.000000e-5, num_features=32)
        self.down_block2_max_pool = nn.AvgPool2d(ceil_mode=False, count_include_pad=True, divisor_override=None, kernel_size=(2,2), padding=(0,0), stride=(2,2))
        self.down_block2_conv1 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.down_block2_relu = nn.LeakyReLU(negative_slope=0.01)
        self.down_block2_conv21 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=64, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.down_block2_conv22 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.pnnx_unique_2 = nn.LeakyReLU(negative_slope=0.01)
        self.down_block2_conv31 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=96, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.down_block2_conv32 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.pnnx_unique_3 = nn.LeakyReLU(negative_slope=0.01)
        self.down_block2_bn = nn.BatchNorm2d(affine=True, eps=1.000000e-5, num_features=32)
        self.down_block3_max_pool = nn.AvgPool2d(ceil_mode=False, count_include_pad=True, divisor_override=None, kernel_size=(2,2), padding=(0,0), stride=(2,2))
        self.down_block3_conv1 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.down_block3_relu = nn.LeakyReLU(negative_slope=0.01)
        self.down_block3_conv21 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=64, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.down_block3_conv22 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.pnnx_unique_4 = nn.LeakyReLU(negative_slope=0.01)
        self.down_block3_conv31 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=96, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.down_block3_conv32 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.pnnx_unique_5 = nn.LeakyReLU(negative_slope=0.01)
        self.down_block3_bn = nn.BatchNorm2d(affine=True, eps=1.000000e-5, num_features=32)
        self.down_block4_max_pool = nn.AvgPool2d(ceil_mode=False, count_include_pad=True, divisor_override=None, kernel_size=(2,2), padding=(0,0), stride=(2,2))
        self.down_block4_conv1 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.down_block4_relu = nn.LeakyReLU(negative_slope=0.01)
        self.down_block4_conv21 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=64, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.down_block4_conv22 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.pnnx_unique_6 = nn.LeakyReLU(negative_slope=0.01)
        self.down_block4_conv31 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=96, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.down_block4_conv32 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.pnnx_unique_7 = nn.LeakyReLU(negative_slope=0.01)
        self.down_block4_bn = nn.BatchNorm2d(affine=True, eps=1.000000e-5, num_features=32)
        self.down_block5_max_pool = nn.AvgPool2d(ceil_mode=False, count_include_pad=True, divisor_override=None, kernel_size=(2,2), padding=(0,0), stride=(2,2))
        self.down_block5_conv1 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.down_block5_relu = nn.LeakyReLU(negative_slope=0.01)
        self.down_block5_conv21 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=64, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.down_block5_conv22 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.pnnx_unique_8 = nn.LeakyReLU(negative_slope=0.01)
        self.down_block5_conv31 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=96, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.down_block5_conv32 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.pnnx_unique_9 = nn.LeakyReLU(negative_slope=0.01)
        self.down_block5_bn = nn.BatchNorm2d(affine=True, eps=1.000000e-5, num_features=32)
        self.up_block1_conv11 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=64, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.up_block1_conv12 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.up_block1_relu = nn.LeakyReLU(negative_slope=0.01)
        self.up_block1_conv21 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=96, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.up_block1_conv22 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.pnnx_unique_10 = nn.LeakyReLU(negative_slope=0.01)
        self.up_block2_conv11 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=64, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.up_block2_conv12 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.up_block2_relu = nn.LeakyReLU(negative_slope=0.01)
        self.up_block2_conv21 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=96, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.up_block2_conv22 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.pnnx_unique_11 = nn.LeakyReLU(negative_slope=0.01)
        self.up_block3_conv11 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=64, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.up_block3_conv12 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.up_block3_relu = nn.LeakyReLU(negative_slope=0.01)
        self.up_block3_conv21 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=96, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.up_block3_conv22 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.pnnx_unique_12 = nn.LeakyReLU(negative_slope=0.01)
        self.up_block4_conv11 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=64, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.up_block4_conv12 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.up_block4_relu = nn.LeakyReLU(negative_slope=0.01)
        self.up_block4_conv21 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=96, kernel_size=(1,1), out_channels=32, padding=(0,0), padding_mode='zeros', stride=(1,1))
        self.up_block4_conv22 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(3,3), out_channels=32, padding=(1,1), padding_mode='zeros', stride=(1,1))
        self.pnnx_unique_13 = nn.LeakyReLU(negative_slope=0.01)
        self.out_conv1 = nn.Conv2d(bias=True, dilation=(1,1), groups=1, in_channels=32, kernel_size=(1,1), out_channels=4, padding=(0,0), padding_mode='zeros', stride=(1,1))

        archive = zipfile.ZipFile('models\ritnet\ritnet320_ts.pnnx.bin', 'r')
        self.down_block1_conv1.bias = self.load_pnnx_bin_as_parameter(archive, 'down_block1.conv1.bias', (32), 'float32')
        self.down_block1_conv1.weight = self.load_pnnx_bin_as_parameter(archive, 'down_block1.conv1.weight', (32,1,3,3), 'float32')
        self.down_block1_conv21.bias = self.load_pnnx_bin_as_parameter(archive, 'down_block1.conv21.bias', (32), 'float32')
        self.down_block1_conv21.weight = self.load_pnnx_bin_as_parameter(archive, 'down_block1.conv21.weight', (32,33,1,1), 'float32')
        self.down_block1_conv22.bias = self.load_pnnx_bin_as_parameter(archive, 'down_block1.conv22.bias', (32), 'float32')
        self.down_block1_conv22.weight = self.load_pnnx_bin_as_parameter(archive, 'down_block1.conv22.weight', (32,32,3,3), 'float32')
        self.down_block1_conv31.bias = self.load_pnnx_bin_as_parameter(archive, 'down_block1.conv31.bias', (32), 'float32')
        self.down_block1_conv31.weight = self.load_pnnx_bin_as_parameter(archive, 'down_block1.conv31.weight', (32,65,1,1), 'float32')
        self.down_block1_conv32.bias = self.load_pnnx_bin_as_parameter(archive, 'down_block1.conv32.bias', (32), 'float32')
        self.down_block1_conv32.weight = self.load_pnnx_bin_as_parameter(archive, 'down_block1.conv32.weight', (32,32,3,3), 'float32')
        self.down_block1_bn.bias = self.load_pnnx_bin_as_parameter(archive, 'down_block1.bn.bias', (32), 'float32')
        self.down_block1_bn.running_mean = self.load_pnnx_bin_as_tensor(archive, 'down_block1.bn.running_mean', (32), 'float32')
        self.down_block1_bn.running_var = self.load_pnnx_bin_as_tensor(archive, 'down_block1.bn.running_var', (32), 'float32')
        self.down_block1_bn.weight = self.load_pnnx_bin_as_parameter(archive, 'down_block1.bn.weight', (32), 'float32')
        self.down_block2_conv1.bias = self.load_pnnx_bin_as_parameter(archive, 'down_block2.conv1.bias', (32), 'float32')
        self.down_block2_conv1.weight = self.load_pnnx_bin_as_parameter(archive, 'down_block2.conv1.weight', (32,32,3,3), 'float32')
        self.down_block2_conv21.bias = self.load_pnnx_bin_as_parameter(archive, 'down_block2.conv21.bias', (32), 'float32')
        self.down_block2_conv21.weight = self.load_pnnx_bin_as_parameter(archive, 'down_block2.conv21.weight', (32,64,1,1), 'float32')
        self.down_block2_conv22.bias = self.load_pnnx_bin_as_parameter(archive, 'down_block2.conv22.bias', (32), 'float32')
        self.down_block2_conv22.weight = self.load_pnnx_bin_as_parameter(archive, 'down_block2.conv22.weight', (32,32,3,3), 'float32')
        self.down_block2_conv31.bias = self.load_pnnx_bin_as_parameter(archive, 'down_block2.conv31.bias', (32), 'float32')
        self.down_block2_conv31.weight = self.load_pnnx_bin_as_parameter(archive, 'down_block2.conv31.weight', (32,96,1,1), 'float32')
        self.down_block2_conv32.bias = self.load_pnnx_bin_as_parameter(archive, 'down_block2.conv32.bias', (32), 'float32')
        self.down_block2_conv32.weight = self.load_pnnx_bin_as_parameter(archive, 'down_block2.conv32.weight', (32,32,3,3), 'float32')
        self.down_block2_bn.bias = self.load_pnnx_bin_as_parameter(archive, 'down_block2.bn.bias', (32), 'float32')
        self.down_block2_bn.running_mean = self.load_pnnx_bin_as_tensor(archive, 'down_block2.bn.running_mean', (32), 'float32')
        self.down_block2_bn.running_var = self.load_pnnx_bin_as_tensor(archive, 'down_block2.bn.running_var', (32), 'float32')
        self.down_block2_bn.weight = self.load_pnnx_bin_as_parameter(archive, 'down_block2.bn.weight', (32), 'float32')
        self.down_block3_conv1.bias = self.load_pnnx_bin_as_parameter(archive, 'down_block3.conv1.bias', (32), 'float32')
        self.down_block3_conv1.weight = self.load_pnnx_bin_as_parameter(archive, 'down_block3.conv1.weight', (32,32,3,3), 'float32')
        self.down_block3_conv21.bias = self.load_pnnx_bin_as_parameter(archive, 'down_block3.conv21.bias', (32), 'float32')
        self.down_block3_conv21.weight = self.load_pnnx_bin_as_parameter(archive, 'down_block3.conv21.weight', (32,64,1,1), 'float32')
        self.down_block3_conv22.bias = self.load_pnnx_bin_as_parameter(archive, 'down_block3.conv22.bias', (32), 'float32')
        self.down_block3_conv22.weight = self.load_pnnx_bin_as_parameter(archive, 'down_block3.conv22.weight', (32,32,3,3), 'float32')
        self.down_block3_conv31.bias = self.load_pnnx_bin_as_parameter(archive, 'down_block3.conv31.bias', (32), 'float32')
        self.down_block3_conv31.weight = self.load_pnnx_bin_as_parameter(archive, 'down_block3.conv31.weight', (32,96,1,1), 'float32')
        self.down_block3_conv32.bias = self.load_pnnx_bin_as_parameter(archive, 'down_block3.conv32.bias', (32), 'float32')
        self.down_block3_conv32.weight = self.load_pnnx_bin_as_parameter(archive, 'down_block3.conv32.weight', (32,32,3,3), 'float32')
        self.down_block3_bn.bias = self.load_pnnx_bin_as_parameter(archive, 'down_block3.bn.bias', (32), 'float32')
        self.down_block3_bn.running_mean = self.load_pnnx_bin_as_tensor(archive, 'down_block3.bn.running_mean', (32), 'float32')
        self.down_block3_bn.running_var = self.load_pnnx_bin_as_tensor(archive, 'down_block3.bn.running_var', (32), 'float32')
        self.down_block3_bn.weight = self.load_pnnx_bin_as_parameter(archive, 'down_block3.bn.weight', (32), 'float32')
        self.down_block4_conv1.bias = self.load_pnnx_bin_as_parameter(archive, 'down_block4.conv1.bias', (32), 'float32')
        self.down_block4_conv1.weight = self.load_pnnx_bin_as_parameter(archive, 'down_block4.conv1.weight', (32,32,3,3), 'float32')
        self.down_block4_conv21.bias = self.load_pnnx_bin_as_parameter(archive, 'down_block4.conv21.bias', (32), 'float32')
        self.down_block4_conv21.weight = self.load_pnnx_bin_as_parameter(archive, 'down_block4.conv21.weight', (32,64,1,1), 'float32')
        self.down_block4_conv22.bias = self.load_pnnx_bin_as_parameter(archive, 'down_block4.conv22.bias', (32), 'float32')
        self.down_block4_conv22.weight = self.load_pnnx_bin_as_parameter(archive, 'down_block4.conv22.weight', (32,32,3,3), 'float32')
        self.down_block4_conv31.bias = self.load_pnnx_bin_as_parameter(archive, 'down_block4.conv31.bias', (32), 'float32')
        self.down_block4_conv31.weight = self.load_pnnx_bin_as_parameter(archive, 'down_block4.conv31.weight', (32,96,1,1), 'float32')
        self.down_block4_conv32.bias = self.load_pnnx_bin_as_parameter(archive, 'down_block4.conv32.bias', (32), 'float32')
        self.down_block4_conv32.weight = self.load_pnnx_bin_as_parameter(archive, 'down_block4.conv32.weight', (32,32,3,3), 'float32')
        self.down_block4_bn.bias = self.load_pnnx_bin_as_parameter(archive, 'down_block4.bn.bias', (32), 'float32')
        self.down_block4_bn.running_mean = self.load_pnnx_bin_as_tensor(archive, 'down_block4.bn.running_mean', (32), 'float32')
        self.down_block4_bn.running_var = self.load_pnnx_bin_as_tensor(archive, 'down_block4.bn.running_var', (32), 'float32')
        self.down_block4_bn.weight = self.load_pnnx_bin_as_parameter(archive, 'down_block4.bn.weight', (32), 'float32')
        self.down_block5_conv1.bias = self.load_pnnx_bin_as_parameter(archive, 'down_block5.conv1.bias', (32), 'float32')
        self.down_block5_conv1.weight = self.load_pnnx_bin_as_parameter(archive, 'down_block5.conv1.weight', (32,32,3,3), 'float32')
        self.down_block5_conv21.bias = self.load_pnnx_bin_as_parameter(archive, 'down_block5.conv21.bias', (32), 'float32')
        self.down_block5_conv21.weight = self.load_pnnx_bin_as_parameter(archive, 'down_block5.conv21.weight', (32,64,1,1), 'float32')
        self.down_block5_conv22.bias = self.load_pnnx_bin_as_parameter(archive, 'down_block5.conv22.bias', (32), 'float32')
        self.down_block5_conv22.weight = self.load_pnnx_bin_as_parameter(archive, 'down_block5.conv22.weight', (32,32,3,3), 'float32')
        self.down_block5_conv31.bias = self.load_pnnx_bin_as_parameter(archive, 'down_block5.conv31.bias', (32), 'float32')
        self.down_block5_conv31.weight = self.load_pnnx_bin_as_parameter(archive, 'down_block5.conv31.weight', (32,96,1,1), 'float32')
        self.down_block5_conv32.bias = self.load_pnnx_bin_as_parameter(archive, 'down_block5.conv32.bias', (32), 'float32')
        self.down_block5_conv32.weight = self.load_pnnx_bin_as_parameter(archive, 'down_block5.conv32.weight', (32,32,3,3), 'float32')
        self.down_block5_bn.bias = self.load_pnnx_bin_as_parameter(archive, 'down_block5.bn.bias', (32), 'float32')
        self.down_block5_bn.running_mean = self.load_pnnx_bin_as_tensor(archive, 'down_block5.bn.running_mean', (32), 'float32')
        self.down_block5_bn.running_var = self.load_pnnx_bin_as_tensor(archive, 'down_block5.bn.running_var', (32), 'float32')
        self.down_block5_bn.weight = self.load_pnnx_bin_as_parameter(archive, 'down_block5.bn.weight', (32), 'float32')
        self.up_block1_conv11.bias = self.load_pnnx_bin_as_parameter(archive, 'up_block1.conv11.bias', (32), 'float32')
        self.up_block1_conv11.weight = self.load_pnnx_bin_as_parameter(archive, 'up_block1.conv11.weight', (32,64,1,1), 'float32')
        self.up_block1_conv12.bias = self.load_pnnx_bin_as_parameter(archive, 'up_block1.conv12.bias', (32), 'float32')
        self.up_block1_conv12.weight = self.load_pnnx_bin_as_parameter(archive, 'up_block1.conv12.weight', (32,32,3,3), 'float32')
        self.up_block1_conv21.bias = self.load_pnnx_bin_as_parameter(archive, 'up_block1.conv21.bias', (32), 'float32')
        self.up_block1_conv21.weight = self.load_pnnx_bin_as_parameter(archive, 'up_block1.conv21.weight', (32,96,1,1), 'float32')
        self.up_block1_conv22.bias = self.load_pnnx_bin_as_parameter(archive, 'up_block1.conv22.bias', (32), 'float32')
        self.up_block1_conv22.weight = self.load_pnnx_bin_as_parameter(archive, 'up_block1.conv22.weight', (32,32,3,3), 'float32')
        self.up_block2_conv11.bias = self.load_pnnx_bin_as_parameter(archive, 'up_block2.conv11.bias', (32), 'float32')
        self.up_block2_conv11.weight = self.load_pnnx_bin_as_parameter(archive, 'up_block2.conv11.weight', (32,64,1,1), 'float32')
        self.up_block2_conv12.bias = self.load_pnnx_bin_as_parameter(archive, 'up_block2.conv12.bias', (32), 'float32')
        self.up_block2_conv12.weight = self.load_pnnx_bin_as_parameter(archive, 'up_block2.conv12.weight', (32,32,3,3), 'float32')
        self.up_block2_conv21.bias = self.load_pnnx_bin_as_parameter(archive, 'up_block2.conv21.bias', (32), 'float32')
        self.up_block2_conv21.weight = self.load_pnnx_bin_as_parameter(archive, 'up_block2.conv21.weight', (32,96,1,1), 'float32')
        self.up_block2_conv22.bias = self.load_pnnx_bin_as_parameter(archive, 'up_block2.conv22.bias', (32), 'float32')
        self.up_block2_conv22.weight = self.load_pnnx_bin_as_parameter(archive, 'up_block2.conv22.weight', (32,32,3,3), 'float32')
        self.up_block3_conv11.bias = self.load_pnnx_bin_as_parameter(archive, 'up_block3.conv11.bias', (32), 'float32')
        self.up_block3_conv11.weight = self.load_pnnx_bin_as_parameter(archive, 'up_block3.conv11.weight', (32,64,1,1), 'float32')
        self.up_block3_conv12.bias = self.load_pnnx_bin_as_parameter(archive, 'up_block3.conv12.bias', (32), 'float32')
        self.up_block3_conv12.weight = self.load_pnnx_bin_as_parameter(archive, 'up_block3.conv12.weight', (32,32,3,3), 'float32')
        self.up_block3_conv21.bias = self.load_pnnx_bin_as_parameter(archive, 'up_block3.conv21.bias', (32), 'float32')
        self.up_block3_conv21.weight = self.load_pnnx_bin_as_parameter(archive, 'up_block3.conv21.weight', (32,96,1,1), 'float32')
        self.up_block3_conv22.bias = self.load_pnnx_bin_as_parameter(archive, 'up_block3.conv22.bias', (32), 'float32')
        self.up_block3_conv22.weight = self.load_pnnx_bin_as_parameter(archive, 'up_block3.conv22.weight', (32,32,3,3), 'float32')
        self.up_block4_conv11.bias = self.load_pnnx_bin_as_parameter(archive, 'up_block4.conv11.bias', (32), 'float32')
        self.up_block4_conv11.weight = self.load_pnnx_bin_as_parameter(archive, 'up_block4.conv11.weight', (32,64,1,1), 'float32')
        self.up_block4_conv12.bias = self.load_pnnx_bin_as_parameter(archive, 'up_block4.conv12.bias', (32), 'float32')
        self.up_block4_conv12.weight = self.load_pnnx_bin_as_parameter(archive, 'up_block4.conv12.weight', (32,32,3,3), 'float32')
        self.up_block4_conv21.bias = self.load_pnnx_bin_as_parameter(archive, 'up_block4.conv21.bias', (32), 'float32')
        self.up_block4_conv21.weight = self.load_pnnx_bin_as_parameter(archive, 'up_block4.conv21.weight', (32,96,1,1), 'float32')
        self.up_block4_conv22.bias = self.load_pnnx_bin_as_parameter(archive, 'up_block4.conv22.bias', (32), 'float32')
        self.up_block4_conv22.weight = self.load_pnnx_bin_as_parameter(archive, 'up_block4.conv22.weight', (32,32,3,3), 'float32')
        self.out_conv1.bias = self.load_pnnx_bin_as_parameter(archive, 'out_conv1.bias', (4), 'float32')
        self.out_conv1.weight = self.load_pnnx_bin_as_parameter(archive, 'out_conv1.weight', (4,32,1,1), 'float32')
        archive.close()

    def load_pnnx_bin_as_parameter(self, archive, key, shape, dtype, requires_grad=True):
        return nn.Parameter(self.load_pnnx_bin_as_tensor(archive, key, shape, dtype), requires_grad)

    def load_pnnx_bin_as_tensor(self, archive, key, shape, dtype):
        fd, tmppath = tempfile.mkstemp()
        with os.fdopen(fd, 'wb') as tmpf, archive.open(key) as keyfile:
            tmpf.write(keyfile.read())
        m = np.memmap(tmppath, dtype=dtype, mode='r', shape=shape).copy()
        os.remove(tmppath)
        return torch.from_numpy(m)

    def forward(self, v_0):
        v_1 = self.down_block1_conv1(v_0)
        v_2 = self.down_block1_relu(v_1)
        v_3 = torch.cat((v_0, v_2), dim=1)
        v_4 = self.down_block1_conv21(v_3)
        v_5 = self.down_block1_conv22(v_4)
        v_6 = self.pnnx_unique_0(v_5)
        v_7 = torch.cat((v_3, v_6), dim=1)
        v_8 = self.down_block1_conv31(v_7)
        v_9 = self.down_block1_conv32(v_8)
        v_10 = self.pnnx_unique_1(v_9)
        v_11 = self.down_block1_bn(v_10)
        v_12 = self.down_block2_max_pool(v_11)
        v_13 = self.down_block2_conv1(v_12)
        v_14 = self.down_block2_relu(v_13)
        v_15 = torch.cat((v_12, v_14), dim=1)
        v_16 = self.down_block2_conv21(v_15)
        v_17 = self.down_block2_conv22(v_16)
        v_18 = self.pnnx_unique_2(v_17)
        v_19 = torch.cat((v_15, v_18), dim=1)
        v_20 = self.down_block2_conv31(v_19)
        v_21 = self.down_block2_conv32(v_20)
        v_22 = self.pnnx_unique_3(v_21)
        v_23 = self.down_block2_bn(v_22)
        v_24 = self.down_block3_max_pool(v_23)
        v_25 = self.down_block3_conv1(v_24)
        v_26 = self.down_block3_relu(v_25)
        v_27 = torch.cat((v_24, v_26), dim=1)
        v_28 = self.down_block3_conv21(v_27)
        v_29 = self.down_block3_conv22(v_28)
        v_30 = self.pnnx_unique_4(v_29)
        v_31 = torch.cat((v_27, v_30), dim=1)
        v_32 = self.down_block3_conv31(v_31)
        v_33 = self.down_block3_conv32(v_32)
        v_34 = self.pnnx_unique_5(v_33)
        v_35 = self.down_block3_bn(v_34)
        v_36 = self.down_block4_max_pool(v_35)
        v_37 = self.down_block4_conv1(v_36)
        v_38 = self.down_block4_relu(v_37)
        v_39 = torch.cat((v_36, v_38), dim=1)
        v_40 = self.down_block4_conv21(v_39)
        v_41 = self.down_block4_conv22(v_40)
        v_42 = self.pnnx_unique_6(v_41)
        v_43 = torch.cat((v_39, v_42), dim=1)
        v_44 = self.down_block4_conv31(v_43)
        v_45 = self.down_block4_conv32(v_44)
        v_46 = self.pnnx_unique_7(v_45)
        v_47 = self.down_block4_bn(v_46)
        v_48 = self.down_block5_max_pool(v_47)
        v_49 = self.down_block5_conv1(v_48)
        v_50 = self.down_block5_relu(v_49)
        v_51 = torch.cat((v_48, v_50), dim=1)
        v_52 = self.down_block5_conv21(v_51)
        v_53 = self.down_block5_conv22(v_52)
        v_54 = self.pnnx_unique_8(v_53)
        v_55 = torch.cat((v_51, v_54), dim=1)
        v_56 = self.down_block5_conv31(v_55)
        v_57 = self.down_block5_conv32(v_56)
        v_58 = self.pnnx_unique_9(v_57)
        v_59 = self.down_block5_bn(v_58)
        v_60 = F.upsample_nearest(v_59, scale_factor=(2.0,2.0))
        v_61 = torch.cat((v_60, v_47), dim=1)
        v_62 = self.up_block1_conv11(v_61)
        v_63 = self.up_block1_conv12(v_62)
        v_64 = self.up_block1_relu(v_63)
        v_65 = torch.cat((v_61, v_64), dim=1)
        v_66 = self.up_block1_conv21(v_65)
        v_67 = self.up_block1_conv22(v_66)
        v_68 = self.pnnx_unique_10(v_67)
        v_69 = F.upsample_nearest(v_68, scale_factor=(2.0,2.0))
        v_70 = torch.cat((v_69, v_35), dim=1)
        v_71 = self.up_block2_conv11(v_70)
        v_72 = self.up_block2_conv12(v_71)
        v_73 = self.up_block2_relu(v_72)
        v_74 = torch.cat((v_70, v_73), dim=1)
        v_75 = self.up_block2_conv21(v_74)
        v_76 = self.up_block2_conv22(v_75)
        v_77 = self.pnnx_unique_11(v_76)
        v_78 = F.upsample_nearest(v_77, scale_factor=(2.0,2.0))
        v_79 = torch.cat((v_78, v_23), dim=1)
        v_80 = self.up_block3_conv11(v_79)
        v_81 = self.up_block3_conv12(v_80)
        v_82 = self.up_block3_relu(v_81)
        v_83 = torch.cat((v_79, v_82), dim=1)
        v_84 = self.up_block3_conv21(v_83)
        v_85 = self.up_block3_conv22(v_84)
        v_86 = self.pnnx_unique_12(v_85)
        v_87 = F.upsample_nearest(v_86, scale_factor=(2.0,2.0))
        v_88 = torch.cat((v_87, v_11), dim=1)
        v_89 = self.up_block4_conv11(v_88)
        v_90 = self.up_block4_conv12(v_89)
        v_91 = self.up_block4_relu(v_90)
        v_92 = torch.cat((v_88, v_91), dim=1)
        v_93 = self.up_block4_conv21(v_92)
        v_94 = self.up_block4_conv22(v_93)
        v_95 = self.pnnx_unique_13(v_94)
        v_96 = self.out_conv1(v_95)
        return v_96

def export_torchscript():
    net = Model()
    net.float()
    net.eval()

    torch.manual_seed(0)
    v_0 = torch.rand(1, 1, 192, 320, dtype=torch.float)

    mod = torch.jit.trace(net, v_0)
    mod.save("models\ritnet\ritnet320_ts_pnnx.py.pt")

def export_onnx():
    net = Model()
    net.float()
    net.eval()

    torch.manual_seed(0)
    v_0 = torch.rand(1, 1, 192, 320, dtype=torch.float)

    torch.onnx.export(net, v_0, "models\ritnet\ritnet320_ts_pnnx.py.onnx", export_params=True, operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK, opset_version=13, input_names=['in0'], output_names=['out0'])

def export_pnnx():
    net = Model()
    net.float()
    net.eval()

    torch.manual_seed(0)
    v_0 = torch.rand(1, 1, 192, 320, dtype=torch.float)

    import pnnx
    pnnx.export(net, "models\ritnet\ritnet320_ts_pnnx.py.pt", v_0)

def export_ncnn():
    export_pnnx()

@torch.no_grad()
def test_inference():
    net = Model()
    net.float()
    net.eval()

    torch.manual_seed(0)
    v_0 = torch.rand(1, 1, 192, 320, dtype=torch.float)

    return net(v_0)

if __name__ == "__main__":
    print(test_inference())
